name = "reccloud-image2-worker"
main = "image2-consumer.js"
compatibility_date = "2026-06-15"

[[kv_namespaces]]
binding = "IMAGE2_JOBS"
id = "e0a59d9f9ece40b9b69e4b104744cbf6"

[[queues.consumers]]
queue = "reccloud-image2-jobs"
max_batch_size = 1
max_batch_timeout = 5
